name: Deploy to Linode
on: 
  push:
    brances: main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-to-Linode-via-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: deploy file
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
            username: 'henrik'
            server: '172.104.147.220'
            ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} 
            local_path: './server.js'
            remote_path: 'projects/testing'
      - name: Restart PM2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: '172.104.147.220'
          username: 'henrik'
          password: ${{ secrets.SSH_PRIVATE_KEY }}
          script: sh restart.sh
        